import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar, Footer } from "@/app/components";
import "@/sass/global.sass"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Store Vision",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  );
}
